import React from 'react';
import { formatDate, money } from '../lib/format';
import { invoiceTotals } from '../lib/invoiceTotals';

/**
 * The invoice as the customer will receive it.
 *
 * This is the on-screen twin of `src/lib/invoicePdf.js`: same sections in the
 * same order, same labels, and the same `money()`/`formatDate()`/`invoiceTotals()`
 * helpers behind every value. The two are checked against each other in
 * `InvoicePreview.test.js`.
 *
 * It is deliberately a plain function of `invoice` -- the PDF is no longer
 * generated by screenshotting this element, so nothing here can change what
 * downloads, and vice versa. Keep them edited in step.
 */
const InvoicePreview = ({ invoice }) => {
  const data = invoice || {};
  const company = data.company || {};
  const client = data.client || {};
  const meta = data.invoice || {};
  const items = Array.isArray(data.items) ? data.items : [];
  const totals = invoiceTotals(data);

  const metaRows = [
    ['Date', formatDate(meta.date)],
    ['Due', formatDate(meta.dueDate)],
    ['Terms', meta.terms],
  ].filter(([, value]) => value);

  return (
    <div id="invoice-preview" className="bg-white text-black rounded-2xl p-4 sm:p-6 md:p-8 shadow-xl h-fit overflow-hidden">
      {/* Header: company block left, invoice metadata right */}
      <div className="flex justify-between items-start gap-6">
        <div className="min-w-0">
          {data.logo && (
            <img src={data.logo} alt="Logo" className="h-12 mb-3 object-contain" />
          )}
          <p className="font-bold text-lg text-gray-800">{company.name}</p>
          <div className="text-sm text-gray-500 mt-1 space-y-0.5">
            <p>{company.address}</p>
            <p>
              {[company.city, company.state].filter(Boolean).join(', ')} {company.zip}
            </p>
            <p>{company.email}</p>
            <p>{company.phone}</p>
          </div>
        </div>

        <div className="text-right shrink-0">
          <h1 className="text-4xl font-bold text-gray-800 tracking-tight">INVOICE</h1>
          <p className="text-lg font-bold text-purple-600 mt-1">#{meta.number}</p>
          <table className="text-sm mt-4 ml-auto">
            <tbody>
              {metaRows.map(([label, value]) => (
                <tr key={label}>
                  <td className="text-gray-500 text-right pr-3">{label}:</td>
                  <td className="font-semibold text-gray-800 text-right whitespace-nowrap">{value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <hr className="my-6 border-gray-300" />

      {/* Bill To */}
      <div className="mb-8">
        <p className="text-xs font-bold text-gray-400 tracking-wider">BILL TO</p>
        <p className="font-bold text-gray-800 mt-2">{client.name || 'Client Name'}</p>
        <div className="text-sm text-gray-500 mt-1 space-y-0.5">
          <p>{client.address || 'Client Address'}</p>
          <p>{client.email || 'client@email.com'}</p>
        </div>
      </div>

      {/* Line items */}
      <div className="overflow-x-auto -mx-2 px-2 my-2">
        <table className="w-full text-sm min-w-[480px] sm:min-w-0">
        <thead>
          <tr className="bg-gray-100 text-xs font-bold text-gray-800 tracking-wider">
            <th className="text-left py-2 px-2 w-[42%]">DESCRIPTION</th>
            <th className="text-center py-2 px-2">DATE</th>
            <th className="text-center py-2 px-2">QTY</th>
            <th className="text-right py-2 px-2">RATE</th>
            <th className="text-right py-2 px-2">AMOUNT</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item, index) => (
            <tr key={index} className="border-b border-gray-200 align-top">
              <td className="py-3 px-2 text-gray-800">{item.description || 'Item description'}</td>
              <td className="py-3 px-2 text-center text-gray-500 whitespace-nowrap">{formatDate(item.date)}</td>
              <td className="py-3 px-2 text-center text-gray-500">{item.quantity}</td>
              <td className="py-3 px-2 text-right text-gray-500 whitespace-nowrap">{money(item.rate)}</td>
              <td className="py-3 px-2 text-right font-semibold text-gray-800 whitespace-nowrap">{money(item.amount)}</td>
            </tr>
          ))}
        </tbody>
      </table>
      </div>

      {/* Totals */}
      <div className="flex justify-end mt-6">
        <table className="text-sm">
          <tbody>
            <tr>
              <td className="text-gray-500 text-right pr-8 py-1">Subtotal</td>
              <td className="font-semibold text-gray-800 text-right py-1 whitespace-nowrap">{money(totals.subtotal)}</td>
            </tr>
            {totals.discountAmount > 0 && (
              <tr className="text-red-600">
                <td className="text-right pr-8 py-1">Discount ({data.discount}%)</td>
                <td className="text-right py-1 whitespace-nowrap">-{money(totals.discountAmount)}</td>
              </tr>
            )}
            {totals.taxAmount > 0 && (
              <tr>
                <td className="text-gray-500 text-right pr-8 py-1">Tax ({data.tax}%)</td>
                <td className="font-semibold text-gray-800 text-right py-1 whitespace-nowrap">{money(totals.taxAmount)}</td>
              </tr>
            )}
            <tr className="border-t border-gray-300">
              <td className="text-lg font-bold text-gray-800 text-right pr-8 pt-3">Total</td>
              <td className="text-lg font-bold text-purple-600 text-right pt-3 whitespace-nowrap">{money(totals.total)}</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Notes */}
      {data.notes && (
        <div className="mt-8 pt-6 border-t border-gray-300">
          <p className="text-xs font-bold text-gray-400 tracking-wider">NOTES</p>
          <p className="text-sm text-gray-500 mt-2 whitespace-pre-wrap">{data.notes}</p>
        </div>
      )}
    </div>
  );
};

export default InvoicePreview;
